// <auto-generated />
using System;
using Accord.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Accord.Domain.Migrations
{
    [DbContext(typeof(AccordContext))]
    [Migration("20260704203744_DropVoiceChannelLeaseCloseReason")]
    partial class DropVoiceChannelLeaseCloseReason
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Accord.Domain.Model.ChannelFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscordChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiscordChannelId", "Type")
                        .IsUnique();

                    b.ToTable("ChannelFlags");
                });

            modelBuilder.Entity("Accord.Domain.Model.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Permission");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Accord.Domain.Model.PromotionCampaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ByUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("ClosedByUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset?>("ClosedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ForUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ToDiscordRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("VoteThresholdRequired")
                        .HasColumnType("integer");

                    b.Property<decimal?>("VouchedByUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("VouchedForByUserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("ByUserId");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("ForUserId");

                    b.HasIndex("VouchedByUserId");

                    b.ToTable("PromotionCampaigns");
                });

            modelBuilder.Entity("Accord.Domain.Model.PromotionCampaignOutput", b =>
                {
                    b.Property<int>("PromotionCampaignId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscordMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("DiscordChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("PromotionCampaignId", "DiscordMessageId", "DiscordChannelId");

                    b.ToTable("PromotionCampaignOutputs");
                });

            modelBuilder.Entity("Accord.Domain.Model.PromotionCampaignVote", b =>
                {
                    b.Property<int>("PromotionCampaignId")
                        .HasColumnType("integer");

                    b.Property<decimal>("VotingUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("AtDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Vote")
                        .HasColumnType("integer");

                    b.HasKey("PromotionCampaignId", "VotingUserId");

                    b.HasIndex("VotingUserId");

                    b.ToTable("PromotionCampaignVotes");
                });

            modelBuilder.Entity("Accord.Domain.Model.RssFeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AddedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscordChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("LastFailedFetchResponse")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastFetchDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextFetchDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfFailedFetches")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RssFeeds");
                });

            modelBuilder.Entity("Accord.Domain.Model.RssFeedPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("PublishedAtDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RssFeedId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RssFeedId");

                    b.ToTable("RssFeedPosts");
                });

            modelBuilder.Entity("Accord.Domain.Model.RunOption", b =>
                {
                    b.Property<int>("Key")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("RunOptions");

                    b.HasData(
                        new
                        {
                            Key = 0,
                            Type = 3,
                            Value = "False"
                        },
                        new
                        {
                            Key = 1,
                            Type = 3,
                            Value = "False"
                        },
                        new
                        {
                            Key = 2,
                            Type = 1,
                            Value = "10"
                        },
                        new
                        {
                            Key = 7,
                            Type = 1,
                            Value = "3"
                        },
                        new
                        {
                            Key = 8,
                            Type = 1,
                            Value = "3"
                        },
                        new
                        {
                            Key = 9,
                            Type = 3,
                            Value = "False"
                        },
                        new
                        {
                            Key = 10,
                            Type = 1,
                            Value = "30"
                        },
                        new
                        {
                            Key = 11,
                            Type = 1,
                            Value = "3"
                        },
                        new
                        {
                            Key = 12,
                            Type = 3,
                            Value = "true"
                        },
                        new
                        {
                            Key = 13,
                            Type = 1,
                            Value = "60"
                        },
                        new
                        {
                            Key = 14,
                            Type = 3,
                            Value = "true"
                        },
                        new
                        {
                            Key = 15,
                            Type = 1,
                            Value = "1440"
                        },
                        new
                        {
                            Key = 16,
                            Type = 3,
                            Value = "false"
                        },
                        new
                        {
                            Key = 17,
                            Type = 1,
                            Value = "5"
                        });
                });

            modelBuilder.Entity("Accord.Domain.Model.StarboardChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DiscordChannelBeingStarredInId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("DiscordStarboardChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("StarboardChannels");
                });

            modelBuilder.Entity("Accord.Domain.Model.StarboardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("StarredDiscordMessageChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("StarredDiscordMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("StarredDiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StarredDiscordUserId");

                    b.ToTable("StarboardEntries");
                });

            modelBuilder.Entity("Accord.Domain.Model.StarboardEntryOutput", b =>
                {
                    b.Property<int>("StarboardEntryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscordMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("DiscordChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("StarboardEntryId", "DiscordMessageId", "DiscordChannelId");

                    b.ToTable("StarboardEntryOutputs");
                });

            modelBuilder.Entity("Accord.Domain.Model.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AddedByUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("AddedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Uses")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Accord.Domain.Model.TagAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AddedByUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("AddedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("TagId");

                    b.ToTable("TagAliases");
                });

            modelBuilder.Entity("Accord.Domain.Model.User", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("FirstSeenDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("JoinedGuildDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeftGuildDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<double>("ParticipationPercentile")
                        .HasColumnType("double precision");

                    b.Property<int>("ParticipationPoints")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipationRank")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("TimedOutUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("VoiceAutoUnmuteAtDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Accord.Domain.Model.UserBotMessage", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("DiscordChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserBotMessages");
                });

            modelBuilder.Entity("Accord.Domain.Model.UserHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AddedByUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("AddedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserHistories");
                });

            modelBuilder.Entity("Accord.Domain.Model.UserMessage", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("AttachmentsDetail")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<decimal>("DiscordChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SentDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserMessages");
                });

            modelBuilder.Entity("Accord.Domain.Model.UserReminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscordChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RemindAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserReminders");
                });

            modelBuilder.Entity("Accord.Domain.Model.VoiceChannelLease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ClosedByUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset?>("ClosedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscordCategoryId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("DiscordChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("DiscordGuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int?>("MaxUsers")
                        .HasColumnType("integer");

                    b.Property<decimal>("OwnerUserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("VoiceChannelLeases");
                });

            modelBuilder.Entity("Accord.Domain.Model.VoiceSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscordChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("DiscordSessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasBeenCountedToXp")
                        .HasColumnType("boolean");

                    b.Property<double?>("MinutesInVoiceChannel")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VoiceConnections");
                });

            modelBuilder.Entity("Accord.Domain.Model.RolePermission", b =>
                {
                    b.HasBaseType("Accord.Domain.Model.Permission");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasIndex("RoleId", "Type")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("RolePermission");
                });

            modelBuilder.Entity("Accord.Domain.Model.UserPermission", b =>
                {
                    b.HasBaseType("Accord.Domain.Model.Permission");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasIndex("UserId", "Type")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("UserPermission");
                });

            modelBuilder.Entity("Accord.Domain.Model.PromotionCampaign", b =>
                {
                    b.HasOne("Accord.Domain.Model.User", "ByUser")
                        .WithMany("PromotionCampaignsByUser")
                        .HasForeignKey("ByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accord.Domain.Model.User", "ClosedByUser")
                        .WithMany("PromotionCampaignsClosedByUser")
                        .HasForeignKey("ClosedByUserId");

                    b.HasOne("Accord.Domain.Model.User", "ForUser")
                        .WithMany("PromotionCampaignsForUser")
                        .HasForeignKey("ForUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accord.Domain.Model.User", "VouchedByUser")
                        .WithMany("PromotionCampaignsVouchedForByUser")
                        .HasForeignKey("VouchedByUserId");

                    b.Navigation("ByUser");

                    b.Navigation("ClosedByUser");

                    b.Navigation("ForUser");

                    b.Navigation("VouchedByUser");
                });

            modelBuilder.Entity("Accord.Domain.Model.PromotionCampaignOutput", b =>
                {
                    b.HasOne("Accord.Domain.Model.PromotionCampaign", "PromotionCampaign")
                        .WithMany("Outputs")
                        .HasForeignKey("PromotionCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromotionCampaign");
                });

            modelBuilder.Entity("Accord.Domain.Model.PromotionCampaignVote", b =>
                {
                    b.HasOne("Accord.Domain.Model.PromotionCampaign", "PromotionCampaign")
                        .WithMany("Votes")
                        .HasForeignKey("PromotionCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accord.Domain.Model.User", "VotingUser")
                        .WithMany("PromotionCampaignsVotes")
                        .HasForeignKey("VotingUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromotionCampaign");

                    b.Navigation("VotingUser");
                });

            modelBuilder.Entity("Accord.Domain.Model.RssFeedPost", b =>
                {
                    b.HasOne("Accord.Domain.Model.RssFeed", "RssFeed")
                        .WithMany("Posts")
                        .HasForeignKey("RssFeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RssFeed");
                });

            modelBuilder.Entity("Accord.Domain.Model.StarboardEntry", b =>
                {
                    b.HasOne("Accord.Domain.Model.User", "StarredDiscordUser")
                        .WithMany()
                        .HasForeignKey("StarredDiscordUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StarredDiscordUser");
                });

            modelBuilder.Entity("Accord.Domain.Model.StarboardEntryOutput", b =>
                {
                    b.HasOne("Accord.Domain.Model.StarboardEntry", "StarboardEntry")
                        .WithMany("Outputs")
                        .HasForeignKey("StarboardEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StarboardEntry");
                });

            modelBuilder.Entity("Accord.Domain.Model.Tag", b =>
                {
                    b.HasOne("Accord.Domain.Model.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");
                });

            modelBuilder.Entity("Accord.Domain.Model.TagAlias", b =>
                {
                    b.HasOne("Accord.Domain.Model.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accord.Domain.Model.Tag", "Tag")
                        .WithMany("Aliases")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Accord.Domain.Model.UserBotMessage", b =>
                {
                    b.HasOne("Accord.Domain.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Accord.Domain.Model.UserHistory", b =>
                {
                    b.HasOne("Accord.Domain.Model.User", "AddedByUser")
                        .WithMany("HistoriesAddedByUser")
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accord.Domain.Model.User", "User")
                        .WithMany("Histories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Accord.Domain.Model.UserMessage", b =>
                {
                    b.HasOne("Accord.Domain.Model.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Accord.Domain.Model.UserReminder", b =>
                {
                    b.HasOne("Accord.Domain.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Accord.Domain.Model.VoiceChannelLease", b =>
                {
                    b.HasOne("Accord.Domain.Model.User", "ClosedByUser")
                        .WithMany("VoiceChannelLeasesClosedByUser")
                        .HasForeignKey("ClosedByUserId");

                    b.HasOne("Accord.Domain.Model.User", "OwnerUser")
                        .WithMany("VoiceChannelLeasesOwned")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClosedByUser");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Accord.Domain.Model.VoiceSession", b =>
                {
                    b.HasOne("Accord.Domain.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Accord.Domain.Model.UserPermission", b =>
                {
                    b.HasOne("Accord.Domain.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Accord.Domain.Model.PromotionCampaign", b =>
                {
                    b.Navigation("Outputs");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Accord.Domain.Model.RssFeed", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Accord.Domain.Model.StarboardEntry", b =>
                {
                    b.Navigation("Outputs");
                });

            modelBuilder.Entity("Accord.Domain.Model.Tag", b =>
                {
                    b.Navigation("Aliases");
                });

            modelBuilder.Entity("Accord.Domain.Model.User", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("HistoriesAddedByUser");

                    b.Navigation("Messages");

                    b.Navigation("PromotionCampaignsByUser");

                    b.Navigation("PromotionCampaignsClosedByUser");

                    b.Navigation("PromotionCampaignsForUser");

                    b.Navigation("PromotionCampaignsVotes");

                    b.Navigation("PromotionCampaignsVouchedForByUser");

                    b.Navigation("VoiceChannelLeasesClosedByUser");

                    b.Navigation("VoiceChannelLeasesOwned");
                });
#pragma warning restore 612, 618
        }
    }
}
