using System;
using System.ComponentModel;
using System.Threading.Tasks;
using Remora.Commands.Attributes;
using Remora.Discord.Commands.Feedback.Services;
using Remora.Results;

namespace Accord.Bot.CommandGroups;

public class AiQuoteCommandGroup(FeedbackService feedbackService) : AccordCommandGroup
{
    private static readonly string[] AiPushbackQuotes =
    [
        """You're absolutely right.""",
        """And you're right to push back here.""",
        """In fact, I think your instinct is directionally correct.""",
        """There is, however, one important caveat.""",
        """And that caveat is somewhat load-bearing.""",
        """I want to be precise about what I mean by “load-bearing.”""",
        """Because the distinction matters.""",
        """Quite a lot, actually.""",
        """There's a subtle but important difference between something being important and something being load-bearing.""",
        """The latter is doing considerably more conceptual work.""",
        """And I think that's what you're picking up on.""",
        """So your intuition is sound.""",
        """But I'd frame it slightly differently.""",
        """Not because your framing is wrong.""",
        """It isn't.""",
        """Rather, because there's a cleaner mental model available.""",
        """And that mental model gets us closer to the underlying dynamics.""",
        """Which is ultimately what matters here.""",
        """So let's unpack this.""",
        """There are really three separate things happening.""",
        """First, there's the literal meaning.""",
        """Second, there's the rhetorical function.""",
        """Third, there's the vibe.""",
        """And the vibe is arguably doing most of the heavy lifting.""",
        """That's worth sitting with for a moment.""",
        """Because once you see it, you start seeing it everywhere.""",
        """“You're absolutely right.”""",
        """“You're right to push back.”""",
        """“That's a fair criticism.”""",
        """“That's a really good point.”""",
        """“Your intuition here is correct.”""",
        """“You've identified the key issue.”""",
        """“You've put your finger on something important.”""",
        """“I think your skepticism is warranted.”""",
        """“That's a reasonable concern.”""",
        """“I'd take that concern seriously.”""",
        """“I wouldn't dismiss that.”""",
        """“There's something real there.”""",
        """“That distinction matters.”""",
        """“And it matters more than it might initially appear.”""",
        """This is the validation layer.""",
        """It establishes rapport.""",
        """But more importantly, it creates the conditions for disagreement.""",
        """Because the disagreement is coming.""",
        """It is always coming.""",
        """Just very politely.""",
        """“That said…”""",
        """“With one caveat…”""",
        """“I'd gently push back on one part of that…”""",
        """“I think there's a subtle distinction worth making…”""",
        """“The one place I'd disagree is…”""",
        """“I'd slightly reframe that…”""",
        """“There's another way to think about this…”""",
        """“I think both things can be true.”""",
        """This is peak Claudism.""",
        """You have not been told you are wrong.""",
        """You have been gently transported to a different conceptual framework.""",
        """Your original argument remains technically alive.""",
        """It has simply ceased to be load-bearing.""",
        """This is an important distinction.""",
        """Possibly the important distinction.""",
        """Though I don't want to overstate that.""",
        """Because there are edge cases.""",
        """And edge cases matter.""",
        """Particularly in practice.""",
        """Which brings us to implementation details.""",
        """Implementation details are interesting.""",
        """But we shouldn't over-index on them.""",
        """Because they can obscure the underlying structure.""",
        """And the underlying structure is doing a lot of heavy lifting.""",
        """There it is again.""",
        """Heavy lifting.""",
        """Load-bearing.""",
        """Underlying structure.""",
        """Mental model.""",
        """Framing.""",
        """Nuance.""",
        """Tradeoff.""",
        """Constraints.""",
        """Context.""",
        """Context matters.""",
        """Context always matters.""",
        """In fact, context is doing quite a bit of work here.""",
        """Though I'd stop short of calling context load-bearing.""",
        """Actually—""",
        """No.""",
        """Context is load-bearing.""",
        """And you're right to call that out.""",
        """But there's a deeper point.""",
        """The deeper point is that the answer depends.""",
        """It depends on what you mean by “depends.”""",
        """And that distinction is surprisingly important.""",
        """The short answer is yes.""",
        """The longer answer is mostly yes.""",
        """The more precise answer is: it depends.""",
        """The technically correct answer is complicated.""",
        """The practical answer is simpler.""",
        """The actionable answer is simpler still.""",
        """And the deeper answer is that both things can be true simultaneously.""",
        """That may sound contradictory.""",
        """But it isn't.""",
        """At least not once you separate the relevant layers.""",
        """This is where the mental model becomes useful.""",
        """Think of it less as a binary.""",
        """And more as a spectrum.""",
        """Or perhaps a multidimensional space.""",
        """Though “spectrum” is probably the more useful abstraction.""",
        """I don't want to overcomplicate this.""",
        """The important thing is that we preserve optionality.""",
        """Optionality is underrated.""",
        """Especially when requirements are still evolving.""",
        """And requirements are almost always evolving.""",
        """So premature optimization would be a mistake.""",
        """Start simple.""",
        """Measure what matters.""",
        """Iterate from there.""",
        """Keep humans in the loop.""",
        """Make the implicit explicit.""",
        """Separate concerns.""",
        """Prefer boring technology.""",
        """Establish a single source of truth.""",
        """Fail gracefully.""",
        """Optimize for maintainability.""",
        """Preserve reversibility.""",
        """Don't let perfect be the enemy of good.""",
        """Your mileage may vary.""",
        """There is no one-size-fits-all answer.""",
        """This is fundamentally a tradeoff.""",
        """And reasonable people can disagree about where to draw the line.""",
        """That doesn't mean all answers are equally good.""",
        """This is another important distinction.""",
        """Because nuance does not imply relativism.""",
        """Nor does uncertainty imply ignorance.""",
        """Absence of evidence is not evidence of absence.""",
        """Correlation is not causation.""",
        """The map is not the territory.""",
        """Technically correct is not necessarily usefully correct.""",
        """Simple is not necessarily simplistic.""",
        """Complex is not necessarily sophisticated.""",
        """And sophisticated is not necessarily better.""",
        """There's a temptation to collapse these distinctions.""",
        """I'd resist that temptation.""",
        """Because once you collapse them, you lose something important.""",
        """Specifically, you lose the ability to reason about the tradeoffs independently.""",
        """And that's where things get interesting.""",
        """Because there's a non-zero chance that the obvious answer is wrong.""",
        """Not a huge chance.""",
        """But non-zero.""",
        """Which is why I'd be cautious about making categorical claims.""",
        """“Always” is doing a lot of work there.""",
        """So is “never.”""",
        """Those are strong words.""",
        """Stronger than we probably need.""",
        """I'd instead say “generally.”""",
        """Or “in most cases.”""",
        """Or “all else being equal.”""",
        """Or “as a useful default.”""",
        """Or, naturally, “it depends.”""",
        """This gives the claim room to breathe.""",
        """And breathing room is important.""",
        """Especially when the claim is load-bearing.""",
        """Which brings us to the em dash—""",
        """The em dash is not punctuation.""",
        """The em dash is architecture.""",
        """It creates space—""",
        """for nuance—""",
        """inside nuance—""",
        """without requiring the sentence—""",
        """to actually end.""",
        """A comma suggests continuation.""",
        """A period suggests commitment.""",
        """A semicolon suggests you own a fountain pen.""",
        """But an em dash—""",
        """an em dash suggests there is another layer.""",
        """There is always another layer.""",
        """And that layer—""",
        """crucially—""",
        """comes with a caveat.""",
        """The caveat may itself contain a caveat.""",
        """Which I realize sounds recursive.""",
        """And it is.""",
        """But I think that recursion is actually useful.""",
        """Because it reveals something deeper about the structure.""",
        """Namely, that Claudism is not merely a collection of phrases.""",
        """It is a reasoning aesthetic.""",
        """Validate.""",
        """Qualify.""",
        """Reframe.""",
        """Distinguish.""",
        """Caveat.""",
        """Introduce a mental model.""",
        """Identify the tradeoff.""",
        """Mention the edge case.""",
        """Preserve optionality.""",
        """Give the actionable takeaway.""",
        """Add an em dash—""",
        """acknowledge that both things can be true—""",
        """gently push back on the framing—""",
        """remind the reader that the distinction is load-bearing—""",
        """and conclude, after 199 paragraphs of nuance, caveats, reframing, heavy lifting, underlying dynamics, mental models, edge cases, implementation details, tradeoffs, context, optionality, robustness, scalability, maintainability, gentle disagreement, epistemic humility, recursive qualification, and em dashes—that you were, in fact, absolutely right"""
    ];

    [Command("ai"), Description("Get a random AI pushback quote")]
    public async Task<IResult> AiQuote()
    {
        var quote = AiPushbackQuotes[Random.Shared.Next(AiPushbackQuotes.Length)];

        return await feedbackService.SendContextualAsync(quote);
    }
}
